### PR TITLE
Small refactor for `PolytrackerPass`

### PR DESCRIPTION
**Pull request by facutuesca**
This replaces ~50 lines of code that implement a custom progress bar with a small header-only 3rd party library that does the same

https://user-images.githubusercontent.com/5762120/166220095-f2a2be9d-b380-4053-a628-9c29d6583c2c.mov

### CODE REVIEW

**Comment by surovic** [comment]
I honestly question the need for this code. If it is indeed desirable, isn't there a library that does exactly this?

**Comment by facutuesca** [comment]
> I honestly question the need for this code. If it is indeed desirable, isn't there a library that does exactly this?
> 
> Edit: perhaps [FTXUI](https://github.com/ArthurSonzogni/FTXUI)

I would guess it's not strictly needed, just a nice to have. Do you think I should remove it on this PR?

**Comment by surovic** [comment]
> I would guess it's not strictly needed, just a nice to have. Do you think I should remove it on this PR?

I would be happier if it wasn't there. But I'd wait for @ESultanik and @hbrodin opinons.

**Comment by facutuesca** [comment]
> I honestly question the need for this code. If it is indeed desirable, isn't there a library that does exactly this?
> 
> Edit: perhaps [FTXUI](https://github.com/ArthurSonzogni/FTXUI)

This is what it could look like using this [small header-only library](https://github.com/p-ranav/indicators):

https://user-images.githubusercontent.com/5762120/166204382-6a37a373-393b-4da8-84ec-9241595e2903.mov

**Comment by surovic** [comment]
This already looks like a much better solution imo.

**Comment by facutuesca** [comment]
> This already looks like a much better solution imo.

@surovic I replaced the progress bar implementation with the new library, let me know how it looks

**Review by surovic — APPROVED** [review]

**Pull request merged**
